### PR TITLE
automaticly get setID

### PR DESCRIPTION
**Pull request by notzastix**
Hey, if you have a discord i would love to work on some blooket stuff with you, you don't seem to be very recognized in the community.
Just respond with your discord.

### CODE REVIEW

**Comment by qaiik** [comment]
I have to go to school currently, but once I get back, I will send you my discord. Just note, I won't be available 24/7 if thats ok.

**Comment by qaiik** [comment]
Thanks!

**Comment by notzastix** [comment]
> I have to go to school currently, but once I get back, I will send you my discord. Just note, I won't be available 24/7 if thats ok.

No problem

> Thanks!

Your welcome

**Comment by qaiik** [comment]
24thdev#6256

**Comment by qaiik** [comment]
By the way, have you seen my updated version qaiik/blkt-reader?

**Pull request merged**
